
package com.hdr.ws.stubs.opportunity;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpportunityService", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpportunityService {


    /**
     * 
     * @param optyId
     * @return
     *     returns com.hdr.ws.stubs.opportunity.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetOpportunity")
    @ResponseWrapper(localName = "getOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetOpportunityResponse")
    public Opportunity getOpportunity(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.hdr.ws.stubs.opportunity.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "createOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateOpportunity")
    @ResponseWrapper(localName = "createOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateOpportunityResponse")
    public Opportunity createOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.hdr.ws.stubs.opportunity.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "updateOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.UpdateOpportunity")
    @ResponseWrapper(localName = "updateOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.UpdateOpportunityResponse")
    public Opportunity updateOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunity")
    @RequestWrapper(localName = "deleteOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunity")
    @ResponseWrapper(localName = "deleteOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityResponse")
    public void deleteOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunity
     * @return
     *     returns com.hdr.ws.stubs.opportunity.Opportunity
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "mergeOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.MergeOpportunity")
    @ResponseWrapper(localName = "mergeOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.MergeOpportunityResponse")
    public Opportunity mergeOpportunity(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param opportunity
     * @param changeOperation
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.opportunity.Opportunity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "processOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessOpportunity")
    @ResponseWrapper(localName = "processOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessOpportunityResponse")
    public List<Opportunity> processOpportunity(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String changeOperation,
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<Opportunity> opportunity,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param processData
     * @return
     *     returns com.hdr.ws.stubs.opportunity.ProcessData
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "processCSOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessCSOpportunity")
    @ResponseWrapper(localName = "processCSOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessCSOpportunityResponse")
    public ProcessData processCSOpportunity(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param processData
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processCSOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "processCSOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessCSOpportunityAsync")
    public void processCSOpportunityAsync(
        @WebParam(name = "processData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessData processData,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param processControl
     * @param opportunity
     * @param changeOperation
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/processOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "processOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.ProcessOpportunityAsync")
    public void processOpportunityAsync(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String changeOperation,
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<Opportunity> opportunity,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        ProcessControl processControl);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityAsync")
    public void deleteOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param optyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "getOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetOpportunityAsync")
    public void getOpportunityAsync(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "createOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateOpportunityAsync")
    public void createOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/mergeOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "mergeOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.MergeOpportunityAsync")
    public void mergeOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunity
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/updateOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "updateOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.UpdateOpportunityAsync")
    public void updateOpportunityAsync(
        @WebParam(name = "opportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Opportunity opportunity);

    /**
     * 
     * @param opportunityCompetitorVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitor")
    @RequestWrapper(localName = "deleteOpportunityCompetitor", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityCompetitor")
    @ResponseWrapper(localName = "deleteOpportunityCompetitorResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityCompetitorResponse")
    public void deleteOpportunityCompetitor(
        @WebParam(name = "opportunityCompetitorVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityCompetitor opportunityCompetitorVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityLeadVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLead")
    @RequestWrapper(localName = "deleteOpportunityLead", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityLead")
    @ResponseWrapper(localName = "deleteOpportunityLeadResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityLeadResponse")
    public void deleteOpportunityLead(
        @WebParam(name = "opportunityLeadVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityLead opportunityLeadVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityReferenceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReference")
    @RequestWrapper(localName = "deleteOpportunityReference", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityReference")
    @ResponseWrapper(localName = "deleteOpportunityReferenceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityReferenceResponse")
    public void deleteOpportunityReference(
        @WebParam(name = "opportunityReferenceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityReference opportunityReferenceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityResourceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResource")
    @RequestWrapper(localName = "deleteOpportunityResource", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityResource")
    @ResponseWrapper(localName = "deleteOpportunityResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityResourceResponse")
    public void deleteOpportunityResource(
        @WebParam(name = "opportunityResourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResource opportunityResourceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityResponseVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponse")
    @RequestWrapper(localName = "deleteOpportunityMktResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityMktResponse")
    @ResponseWrapper(localName = "deleteOpportunityMktResponseResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityMktResponseResponse")
    public void deleteOpportunityMktResponse(
        @WebParam(name = "opportunityResponseVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResponse opportunityResponseVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityRevenueVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenue")
    @RequestWrapper(localName = "deleteOpportunityRevenue", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityRevenue")
    @ResponseWrapper(localName = "deleteOpportunityRevenueResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityRevenueResponse")
    public void deleteOpportunityRevenue(
        @WebParam(name = "opportunityRevenueVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Revenue opportunityRevenueVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunitySourceVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySource")
    @RequestWrapper(localName = "deleteOpportunitySource", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunitySource")
    @ResponseWrapper(localName = "deleteOpportunitySourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunitySourceResponse")
    public void deleteOpportunitySource(
        @WebParam(name = "opportunitySourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunitySource opportunitySourceVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityCompetitorVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityCompetitorAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityCompetitorAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityCompetitorAsync")
    public void deleteOpportunityCompetitorAsync(
        @WebParam(name = "opportunityCompetitorVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityCompetitor opportunityCompetitorVO);

    /**
     * 
     * @param opportunityResponseVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityMktResponseAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityMktResponseAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityMktResponseAsync")
    public void deleteOpportunityMktResponseAsync(
        @WebParam(name = "opportunityResponseVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResponse opportunityResponseVO);

    /**
     * 
     * @param opportunityRevenueVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityRevenueAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityRevenueAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityRevenueAsync")
    public void deleteOpportunityRevenueAsync(
        @WebParam(name = "opportunityRevenueVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        Revenue opportunityRevenueVO);

    /**
     * 
     * @param opportunityResourceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityResourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityResourceAsync")
    public void deleteOpportunityResourceAsync(
        @WebParam(name = "opportunityResourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityResource opportunityResourceVO);

    /**
     * 
     * @param opportunityLeadVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityLeadAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityLeadAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityLeadAsync")
    public void deleteOpportunityLeadAsync(
        @WebParam(name = "opportunityLeadVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityLead opportunityLeadVO);

    /**
     * 
     * @param opportunitySourceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunitySourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunitySourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunitySourceAsync")
    public void deleteOpportunitySourceAsync(
        @WebParam(name = "opportunitySourceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunitySource opportunitySourceVO);

    /**
     * 
     * @param opportunityReferenceVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityReferenceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityReferenceAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityReferenceAsync")
    public void deleteOpportunityReferenceAsync(
        @WebParam(name = "opportunityReferenceVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityReference opportunityReferenceVO);

    /**
     * 
     * @param optyId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronously")
    @RequestWrapper(localName = "doAutoAssignmentAsynchronously", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DoAutoAssignmentAsynchronously")
    @ResponseWrapper(localName = "doAutoAssignmentAsynchronouslyResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DoAutoAssignmentAsynchronouslyResponse")
    public void doAutoAssignmentAsynchronously(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String optyId)
        throws ServiceException
    ;

    /**
     * 
     * @param optyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/doAutoAssignmentAsynchronouslyAsync")
    @Oneway
    @RequestWrapper(localName = "doAutoAssignmentAsynchronouslyAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DoAutoAssignmentAsynchronouslyAsync")
    public void doAutoAssignmentAsynchronouslyAsync(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String optyId);

    /**
     * 
     * @param opportunityContactVO
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContact")
    @RequestWrapper(localName = "deleteOpportunityContact", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityContact")
    @ResponseWrapper(localName = "deleteOpportunityContactResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityContactResponse")
    public void deleteOpportunityContact(
        @WebParam(name = "opportunityContactVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityContact opportunityContactVO)
        throws ServiceException
    ;

    /**
     * 
     * @param opportunityContactVO
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteOpportunityContactAsync")
    @Oneway
    @RequestWrapper(localName = "deleteOpportunityContactAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteOpportunityContactAsync")
    public void deleteOpportunityContactAsync(
        @WebParam(name = "opportunityContactVO", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        OpportunityContact opportunityContactVO);

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.opportunity.Opportunity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "findOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.FindOpportunity")
    @ResponseWrapper(localName = "findOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.FindOpportunityResponse")
    public List<Opportunity> findOpportunity(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/findOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "findOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.FindOpportunityAsync")
    public void findOpportunityAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        FindControl findControl);

    /**
     * 
     * @param salesAccountId
     * @return
     *     returns boolean
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "isSalesAccountUsedInOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.IsSalesAccountUsedInOpportunity")
    @ResponseWrapper(localName = "isSalesAccountUsedInOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.IsSalesAccountUsedInOpportunityResponse")
    public boolean isSalesAccountUsedInOpportunity(
        @WebParam(name = "salesAccountId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long salesAccountId)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/isSalesAccountUsedInOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "isSalesAccountUsedInOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.IsSalesAccountUsedInOpportunityAsync")
    public void isSalesAccountUsedInOpportunityAsync(
        @WebParam(name = "salesAccountId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long salesAccountId);

    /**
     * 
     * @param deleteEntities
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.opportunity.DeleteEntity>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraint")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "checkConstraint", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CheckConstraint")
    @ResponseWrapper(localName = "checkConstraintResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CheckConstraintResponse")
    public List<DeleteEntity> checkConstraint(
        @WebParam(name = "deleteEntities", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<DeleteEntity> deleteEntities)
        throws ServiceException
    ;

    /**
     * 
     * @param deleteEntities
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/checkConstraintAsync")
    @Oneway
    @RequestWrapper(localName = "checkConstraintAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CheckConstraintAsync")
    public void checkConstraintAsync(
        @WebParam(name = "deleteEntities", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<DeleteEntity> deleteEntities);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.hdr.ws.stubs.opportunity.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.opportunity.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

    /**
     * 
     * @param commitData
     * @param attachmentRows
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createAttachment")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "createAttachment", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateAttachment")
    @ResponseWrapper(localName = "createAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateAttachmentResponse")
    public String createAttachment(
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> attachmentRows,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData)
        throws ServiceException
    ;

    /**
     * 
     * @param commitData
     * @param attachmentRows
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/createAttachmentAsync")
    @Oneway
    @RequestWrapper(localName = "createAttachmentAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CreateAttachmentAsync")
    public void createAttachmentAsync(
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> attachmentRows,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData);

    /**
     * 
     * @param commitData
     * @param attachmentRows
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/copyAttachment")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "copyAttachment", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CopyAttachment")
    @ResponseWrapper(localName = "copyAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CopyAttachmentResponse")
    public String copyAttachment(
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> attachmentRows,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData)
        throws ServiceException
    ;

    /**
     * 
     * @param commitData
     * @param attachmentRows
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/copyAttachmentAsync")
    @Oneway
    @RequestWrapper(localName = "copyAttachmentAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.CopyAttachmentAsync")
    public void copyAttachmentAsync(
        @WebParam(name = "attachmentRows", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> attachmentRows,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData);

    /**
     * 
     * @param commitData
     * @param deleteParams
     * @return
     *     returns java.lang.String
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteAttachment")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "deleteAttachment", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAttachment")
    @ResponseWrapper(localName = "deleteAttachmentResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAttachmentResponse")
    public String deleteAttachment(
        @WebParam(name = "deleteParams", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> deleteParams,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData)
        throws ServiceException
    ;

    /**
     * 
     * @param commitData
     * @param deleteParams
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteAttachmentAsync")
    @Oneway
    @RequestWrapper(localName = "deleteAttachmentAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAttachmentAsync")
    public void deleteAttachmentAsync(
        @WebParam(name = "deleteParams", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> deleteParams,
        @WebParam(name = "commitData", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        String commitData);

    /**
     * 
     * @param getParameters
     * @return
     *     returns com.hdr.ws.stubs.opportunity.CommonAttachments
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getAttachmentContent")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getAttachmentContent", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentContent")
    @ResponseWrapper(localName = "getAttachmentContentResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentContentResponse")
    public CommonAttachments getAttachmentContent(
        @WebParam(name = "getParameters", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        CommonAttachments getParameters)
        throws ServiceException
    ;

    /**
     * 
     * @param getParameters
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getAttachmentContentAsync")
    @Oneway
    @RequestWrapper(localName = "getAttachmentContentAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentContentAsync")
    public void getAttachmentContentAsync(
        @WebParam(name = "getParameters", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        CommonAttachments getParameters);

    /**
     * 
     * @param getParameters
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.opportunity.CommonAttachments>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getAttachmentsListWithoutContent")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
    @RequestWrapper(localName = "getAttachmentsListWithoutContent", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentsListWithoutContent")
    @ResponseWrapper(localName = "getAttachmentsListWithoutContentResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentsListWithoutContentResponse")
    public List<CommonAttachments> getAttachmentsListWithoutContent(
        @WebParam(name = "getParameters", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> getParameters)
        throws ServiceException
    ;

    /**
     * 
     * @param getParameters
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/getAttachmentsListWithoutContentAsync")
    @Oneway
    @RequestWrapper(localName = "getAttachmentsListWithoutContentAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.GetAttachmentsListWithoutContentAsync")
    public void getAttachmentsListWithoutContentAsync(
        @WebParam(name = "getParameters", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        List<CommonAttachments> getParameters);

    /**
     * 
     * @param optyId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteAllRevenuesInOpportunity")
    @RequestWrapper(localName = "deleteAllRevenuesInOpportunity", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAllRevenuesInOpportunity")
    @ResponseWrapper(localName = "deleteAllRevenuesInOpportunityResponse", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAllRevenuesInOpportunityResponse")
    public void deleteAllRevenuesInOpportunity(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId)
        throws ServiceException
    ;

    /**
     * 
     * @param optyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/deleteAllRevenuesInOpportunityAsync")
    @Oneway
    @RequestWrapper(localName = "deleteAllRevenuesInOpportunityAsync", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/", className = "com.hdr.ws.stubs.opportunity.DeleteAllRevenuesInOpportunityAsync")
    public void deleteAllRevenuesInOpportunityAsync(
        @WebParam(name = "optyId", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/types/")
        long optyId);

}
