
package com.hdr.ws.stubs.opportunity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpportunityService", targetNamespace = "http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/", wsdlLocation = "https://caye-test.crm.us2.oraclecloud.com/opptyMgmtOpportunities/OpportunityService?wsdl")
public class OpportunityService_Service
    extends Service
{

    private final static URL OPPORTUNITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPPORTUNITYSERVICE_EXCEPTION;
    private final static QName OPPORTUNITYSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/", "OpportunityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://caye-test.crm.us2.oraclecloud.com/opptyMgmtOpportunities/OpportunityService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPPORTUNITYSERVICE_WSDL_LOCATION = url;
        OPPORTUNITYSERVICE_EXCEPTION = e;
    }

    public OpportunityService_Service() {
        super(__getWsdlLocation(), OPPORTUNITYSERVICE_QNAME);
    }

    public OpportunityService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPPORTUNITYSERVICE_QNAME, features);
    }

    public OpportunityService_Service(URL wsdlLocation) {
        super(wsdlLocation, OPPORTUNITYSERVICE_QNAME);
    }

    public OpportunityService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPPORTUNITYSERVICE_QNAME, features);
    }

    public OpportunityService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpportunityService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpportunityService
     */
    @WebEndpoint(name = "OpportunityServiceSoapHttpPort")
    public OpportunityService getOpportunityServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/", "OpportunityServiceSoapHttpPort"), OpportunityService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpportunityService
     */
    @WebEndpoint(name = "OpportunityServiceSoapHttpPort")
    public OpportunityService getOpportunityServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/sales/opptyMgmt/opportunities/opportunityService/", "OpportunityServiceSoapHttpPort"), OpportunityService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPPORTUNITYSERVICE_EXCEPTION!= null) {
            throw OPPORTUNITYSERVICE_EXCEPTION;
        }
        return OPPORTUNITYSERVICE_WSDL_LOCATION;
    }

}
