
package com.serene.pdms.ws.stubs.company;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalesPartyService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/", wsdlLocation = "https://caye-test.crm.us2.oraclecloud.com/crmCommonSalesParties/SalesPartyService?WSDL")
public class SalesPartyService_Service
    extends Service
{

    private final static URL SALESPARTYSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESPARTYSERVICE_EXCEPTION;
    private final static QName SALESPARTYSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/", "SalesPartyService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://caye-test.crm.us2.oraclecloud.com/crmCommonSalesParties/SalesPartyService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESPARTYSERVICE_WSDL_LOCATION = url;
        SALESPARTYSERVICE_EXCEPTION = e;
    }

    public SalesPartyService_Service() {
        super(__getWsdlLocation(), SALESPARTYSERVICE_QNAME);
    }

    public SalesPartyService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESPARTYSERVICE_QNAME, features);
    }

    public SalesPartyService_Service(URL wsdlLocation) {
        super(wsdlLocation, SALESPARTYSERVICE_QNAME);
    }

    public SalesPartyService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESPARTYSERVICE_QNAME, features);
    }

    public SalesPartyService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesPartyService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalesPartyService
     */
    @WebEndpoint(name = "SalesPartyServiceSoapHttpPort")
    public SalesPartyService getSalesPartyServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/", "SalesPartyServiceSoapHttpPort"), SalesPartyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesPartyService
     */
    @WebEndpoint(name = "SalesPartyServiceSoapHttpPort")
    public SalesPartyService getSalesPartyServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/", "SalesPartyServiceSoapHttpPort"), SalesPartyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESPARTYSERVICE_EXCEPTION!= null) {
            throw SALESPARTYSERVICE_EXCEPTION;
        }
        return SALESPARTYSERVICE_WSDL_LOCATION;
    }

}
