
package com.serene.pdms.ws.stubs.company;

import java.util.List;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SalesPartyService", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SalesPartyService {


    /**
     * 
     * @param operation
     * @param saveFlag
     * @param partyId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfile")
    @RequestWrapper(localName = "assignSalesAccountChkProfile", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.AssignSalesAccountChkProfile")
    @ResponseWrapper(localName = "assignSalesAccountChkProfileResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.AssignSalesAccountChkProfileResponse")
    public void assignSalesAccountChkProfile(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId,
        @WebParam(name = "operation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String operation,
        @WebParam(name = "saveFlag", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        boolean saveFlag)
        throws ServiceException
    ;

    /**
     * 
     * @param endId
     * @param startId
     * @param schTime
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlag")
    @RequestWrapper(localName = "updateExistingFlag", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateExistingFlag")
    @ResponseWrapper(localName = "updateExistingFlagResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateExistingFlagResponse")
    public void updateExistingFlag(
        @WebParam(name = "startId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long startId,
        @WebParam(name = "endId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long endId,
        @WebParam(name = "schTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long schTime)
        throws ServiceException
    ;

    /**
     * 
     * @param organizationParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.OrganizationPartyResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "createOrganizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateOrganizationParty")
    @ResponseWrapper(localName = "createOrganizationPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateOrganizationPartyResponse")
    public OrganizationPartyResult createOrganizationParty(
        @WebParam(name = "organizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        OrganizationParty organizationParty)
        throws ServiceException
    ;

    /**
     * 
     * @param organizationParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.OrganizationPartyResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "mergeOrganizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeOrganizationParty")
    @ResponseWrapper(localName = "mergeOrganizationPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeOrganizationPartyResponse")
    public OrganizationPartyResult mergeOrganizationParty(
        @WebParam(name = "organizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        OrganizationParty organizationParty)
        throws ServiceException
    ;

    /**
     * 
     * @param personParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.PersonResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "createPersonParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePersonParty")
    @ResponseWrapper(localName = "createPersonPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePersonPartyResponse")
    public PersonResult createPersonParty(
        @WebParam(name = "personParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        Person personParty)
        throws ServiceException
    ;

    /**
     * 
     * @param personParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.PersonResult
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "mergePersonParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergePersonParty")
    @ResponseWrapper(localName = "mergePersonPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergePersonPartyResponse")
    public PersonResult mergePersonParty(
        @WebParam(name = "personParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        Person personParty)
        throws ServiceException
    ;

    /**
     * 
     * @param partyId
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getSalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccount")
    @ResponseWrapper(localName = "getSalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccountResponse")
    public SalesAccount getSalesAccount(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccount
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "createSalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccount")
    @ResponseWrapper(localName = "createSalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccountResponse")
    public SalesAccount createSalesAccount(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccount
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "updateSalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccount")
    @ResponseWrapper(localName = "updateSalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccountResponse")
    public SalesAccount updateSalesAccount(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccount
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccount
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "mergeSalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeSalesAccount")
    @ResponseWrapper(localName = "mergeSalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeSalesAccountResponse")
    public SalesAccount mergeSalesAccount(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.SalesAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findSalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccount")
    @ResponseWrapper(localName = "findSalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResponse")
    public List<SalesAccount> findSalesAccount(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "createSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccountResource")
    @ResponseWrapper(localName = "createSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccountResourceResponse")
    public SalesAccountResource createSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "updateSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccountResource")
    @ResponseWrapper(localName = "updateSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccountResourceResponse")
    public SalesAccountResource updateSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResource")
    @RequestWrapper(localName = "deleteSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesAccountResource")
    @ResponseWrapper(localName = "deleteSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesAccountResourceResponse")
    public void deleteSalesAccountResource(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.SalesAccountResource>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResource")
    @ResponseWrapper(localName = "findSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResourceResponse")
    public List<SalesAccountResource> findSalesAccountResource(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.SalesAccountResourceAccess>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccess")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findSalesAccountResourceAccess", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResourceAccess")
    @ResponseWrapper(localName = "findSalesAccountResourceAccessResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResourceAccessResponse")
    public List<SalesAccountResourceAccess> findSalesAccountResourceAccess(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param partyId
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesParty
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getSalesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesParty")
    @ResponseWrapper(localName = "getSalesPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesPartyResponse")
    public SalesParty getSalesParty(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId)
        throws ServiceException
    ;

    /**
     * 
     * @param salesParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesParty
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "createSalesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesParty")
    @ResponseWrapper(localName = "createSalesPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesPartyResponse")
    public SalesParty createSalesParty(
        @WebParam(name = "salesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesParty salesParty)
        throws ServiceException
    ;

    /**
     * 
     * @param salesParty
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesParty
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "updateSalesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesParty")
    @ResponseWrapper(localName = "updateSalesPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesPartyResponse")
    public SalesParty updateSalesParty(
        @WebParam(name = "salesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesParty salesParty)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.SalesParty>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesParty")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findSalesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesParty")
    @ResponseWrapper(localName = "findSalesPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesPartyResponse")
    public List<SalesParty> findSalesParty(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "updateSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccountResourceAsync")
    public void updateSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "findSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResourceAsync")
    public void findSalesAccountResourceAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param organizationParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createOrganizationPartyAsync")
    @Oneway
    @RequestWrapper(localName = "createOrganizationPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateOrganizationPartyAsync")
    public void createOrganizationPartyAsync(
        @WebParam(name = "organizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        OrganizationParty organizationParty);

    /**
     * 
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesPartyAsync")
    @Oneway
    @RequestWrapper(localName = "getSalesPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesPartyAsync")
    public void getSalesPartyAsync(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId);

    /**
     * 
     * @param organizationParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeOrganizationPartyAsync")
    @Oneway
    @RequestWrapper(localName = "mergeOrganizationPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeOrganizationPartyAsync")
    public void mergeOrganizationPartyAsync(
        @WebParam(name = "organizationParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        OrganizationParty organizationParty);

    /**
     * 
     * @param endId
     * @param startId
     * @param schTime
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateExistingFlagAsync")
    @Oneway
    @RequestWrapper(localName = "updateExistingFlagAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateExistingFlagAsync")
    public void updateExistingFlagAsync(
        @WebParam(name = "startId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long startId,
        @WebParam(name = "endId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long endId,
        @WebParam(name = "schTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long schTime);

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "createSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccountResourceAsync")
    public void createSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "findSalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountAsync")
    public void findSalesAccountAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param personParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergePersonPartyAsync")
    @Oneway
    @RequestWrapper(localName = "mergePersonPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergePersonPartyAsync")
    public void mergePersonPartyAsync(
        @WebParam(name = "personParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        Person personParty);

    /**
     * 
     * @param operation
     * @param saveFlag
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/assignSalesAccountChkProfileAsync")
    @Oneway
    @RequestWrapper(localName = "assignSalesAccountChkProfileAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.AssignSalesAccountChkProfileAsync")
    public void assignSalesAccountChkProfileAsync(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId,
        @WebParam(name = "operation", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String operation,
        @WebParam(name = "saveFlag", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        boolean saveFlag);

    /**
     * 
     * @param personParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPersonPartyAsync")
    @Oneway
    @RequestWrapper(localName = "createPersonPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePersonPartyAsync")
    public void createPersonPartyAsync(
        @WebParam(name = "personParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        Person personParty);

    /**
     * 
     * @param salesAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "createSalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesAccountAsync")
    public void createSalesAccountAsync(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount);

    /**
     * 
     * @param salesAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "updateSalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesAccountAsync")
    public void updateSalesAccountAsync(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount);

    /**
     * 
     * @param salesAccountResource
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "deleteSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesAccountResourceAsync")
    public void deleteSalesAccountResourceAsync(
        @WebParam(name = "salesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccountResource salesAccountResource);

    /**
     * 
     * @param salesAccount
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/mergeSalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "mergeSalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.MergeSalesAccountAsync")
    public void mergeSalesAccountAsync(
        @WebParam(name = "salesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesAccount salesAccount);

    /**
     * 
     * @param salesParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createSalesPartyAsync")
    @Oneway
    @RequestWrapper(localName = "createSalesPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreateSalesPartyAsync")
    public void createSalesPartyAsync(
        @WebParam(name = "salesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesParty salesParty);

    /**
     * 
     * @param salesParty
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/updateSalesPartyAsync")
    @Oneway
    @RequestWrapper(localName = "updateSalesPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.UpdateSalesPartyAsync")
    public void updateSalesPartyAsync(
        @WebParam(name = "salesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        SalesParty salesParty);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountResourceAccessAsync")
    @Oneway
    @RequestWrapper(localName = "findSalesAccountResourceAccessAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountResourceAccessAsync")
    public void findSalesAccountResourceAccessAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesPartyAsync")
    @Oneway
    @RequestWrapper(localName = "findSalesPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesPartyAsync")
    public void findSalesPartyAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "getSalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccountAsync")
    public void getSalesAccountAsync(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId);

    /**
     * 
     * @param sAccountResourceId
     * @return
     *     returns com.serene.pdms.ws.stubs.company.SalesAccountResource
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResource")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getSalesAccountResource", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccountResource")
    @ResponseWrapper(localName = "getSalesAccountResourceResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccountResourceResponse")
    public SalesAccountResource getSalesAccountResource(
        @WebParam(name = "sAccountResourceId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long sAccountResourceId)
        throws ServiceException
    ;

    /**
     * 
     * @param sAccountResourceId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getSalesAccountResourceAsync")
    @Oneway
    @RequestWrapper(localName = "getSalesAccountResourceAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetSalesAccountResourceAsync")
    public void getSalesAccountResourceAsync(
        @WebParam(name = "sAccountResourceId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long sAccountResourceId);

    /**
     * 
     * @param partyId
     * @param partyUsage
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsage")
    @RequestWrapper(localName = "createPartyUsage", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePartyUsage")
    @ResponseWrapper(localName = "createPartyUsageResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePartyUsageResponse")
    public void createPartyUsage(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId,
        @WebParam(name = "partyUsage", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String partyUsage)
        throws ServiceException
    ;

    /**
     * 
     * @param partyId
     * @param partyUsage
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/createPartyUsageAsync")
    @Oneway
    @RequestWrapper(localName = "createPartyUsageAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.CreatePartyUsageAsync")
    public void createPartyUsageAsync(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId,
        @WebParam(name = "partyUsage", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String partyUsage);

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.MySalesAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccount")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findMySalesAccount", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccount")
    @ResponseWrapper(localName = "findMySalesAccountResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountResponse")
    public List<MySalesAccount> findMySalesAccount(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountAsync")
    @Oneway
    @RequestWrapper(localName = "findMySalesAccountAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountAsync")
    public void findMySalesAccountAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.MySalesAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVC")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findMySalesAccountMyTeamVC", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyTeamVC")
    @ResponseWrapper(localName = "findMySalesAccountMyTeamVCResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyTeamVCResponse")
    public List<MySalesAccount> findMySalesAccountMyTeamVC(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.MySalesAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVC")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findMySalesAccountMyVC", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyVC")
    @ResponseWrapper(localName = "findMySalesAccountMyVCResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyVCResponse")
    public List<MySalesAccount> findMySalesAccountMyVC(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyVCAsync")
    @Oneway
    @RequestWrapper(localName = "findMySalesAccountMyVCAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyVCAsync")
    public void findMySalesAccountMyVCAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param findControl
     * @param findCriteria
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findMySalesAccountMyTeamVCAsync")
    @Oneway
    @RequestWrapper(localName = "findMySalesAccountMyTeamVCAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindMySalesAccountMyTeamVCAsync")
    public void findMySalesAccountMyTeamVCAsync(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl);

    /**
     * 
     * @param findControl
     * @param bindCity
     * @param bindPostalCode
     * @param bindOwner
     * @param bindCountry
     * @param bindPartyUniqueName
     * @param bindResourcePartyName
     * @param bindState
     * @param bindTerritory
     * @param bindAddress1
     * @param bindPartyNumber
     * @param bindAddress2
     * @param findCriteria
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.SalesAccount>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVC")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "findSalesAccountMyFavoriteSalesAccountsVC", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountMyFavoriteSalesAccountsVC")
    @ResponseWrapper(localName = "findSalesAccountMyFavoriteSalesAccountsVCResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.FindSalesAccountMyFavoriteSalesAccountsVCResponse")
    public List<SalesAccount> findSalesAccountMyFavoriteSalesAccountsVC(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "BindPartyUniqueName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindPartyUniqueName,
        @WebParam(name = "BindOwner", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindOwner,
        @WebParam(name = "BindPartyNumber", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindPartyNumber,
        @WebParam(name = "BindAddress1", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindAddress1,
        @WebParam(name = "BindAddress2", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindAddress2,
        @WebParam(name = "BindCity", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindCity,
        @WebParam(name = "BindState", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindState,
        @WebParam(name = "BindPostalCode", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindPostalCode,
        @WebParam(name = "BindCountry", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindCountry,
        @WebParam(name = "BindResourcePartyName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindResourcePartyName,
        @WebParam(name = "BindTerritory", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String bindTerritory,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        FindControl findControl)
        throws ServiceException
    ;

    /**
     * 
     * @param parameters
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/findSalesAccountMyFavoriteSalesAccountsVCAsync")
    @Oneway
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public void findSalesAccountMyFavoriteSalesAccountsVCAsync(
        @WebParam(name = "findSalesAccountMyFavoriteSalesAccountsVC", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", partName = "parameters")
        FindSalesAccountMyFavoriteSalesAccountsVC parameters);

    /**
     * 
     * @param partyId
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesParty")
    @RequestWrapper(localName = "deleteSalesParty", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesParty")
    @ResponseWrapper(localName = "deleteSalesPartyResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesPartyResponse")
    public void deleteSalesParty(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId)
        throws ServiceException
    ;

    /**
     * 
     * @param partyId
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/deleteSalesPartyAsync")
    @Oneway
    @RequestWrapper(localName = "deleteSalesPartyAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.DeleteSalesPartyAsync")
    public void deleteSalesPartyAsync(
        @WebParam(name = "partyId", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        long partyId);

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.serene.pdms.ws.stubs.company.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.serene.pdms.ws.stubs.company.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

    /**
     * 
     * @param viewName
     * @param localeName
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getDfltObjAttrHintsAsync")
    @Oneway
    @RequestWrapper(localName = "getDfltObjAttrHintsAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetDfltObjAttrHintsAsync")
    public void getDfltObjAttrHintsAsync(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/")
        String localeName);

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getEntityListAsync")
    @Oneway
    @RequestWrapper(localName = "getEntityListAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetEntityListAsync")
    public void getEntityListAsync();

    /**
     * 
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/getServiceLastUpdateTimeAsync")
    @Oneway
    @RequestWrapper(localName = "getServiceLastUpdateTimeAsync", targetNamespace = "http://xmlns.oracle.com/apps/crmCommon/salesParties/salesPartiesService/types/", className = "com.serene.pdms.ws.stubs.company.GetServiceLastUpdateTimeAsync")
    public void getServiceLastUpdateTimeAsync();

}
