
package com.hdr.ws.stubs.customeObject;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SalesCustomObjectService", targetNamespace = "http://xmlns.oracle.com/apps/sales/custExtn/extnService/", wsdlLocation = "https://caye-test.crm.us2.oraclecloud.com/opptyMgmtExtensibility/SalesCustomObjectService?WSDL")
public class SalesCustomObjectService_Service
    extends Service
{

    private final static URL SALESCUSTOMOBJECTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SALESCUSTOMOBJECTSERVICE_EXCEPTION;
    private final static QName SALESCUSTOMOBJECTSERVICE_QNAME = new QName("http://xmlns.oracle.com/apps/sales/custExtn/extnService/", "SalesCustomObjectService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://caye-test.crm.us2.oraclecloud.com/opptyMgmtExtensibility/SalesCustomObjectService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SALESCUSTOMOBJECTSERVICE_WSDL_LOCATION = url;
        SALESCUSTOMOBJECTSERVICE_EXCEPTION = e;
    }

    public SalesCustomObjectService_Service() {
        super(__getWsdlLocation(), SALESCUSTOMOBJECTSERVICE_QNAME);
    }

    public SalesCustomObjectService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SALESCUSTOMOBJECTSERVICE_QNAME, features);
    }

    public SalesCustomObjectService_Service(URL wsdlLocation) {
        super(wsdlLocation, SALESCUSTOMOBJECTSERVICE_QNAME);
    }

    public SalesCustomObjectService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SALESCUSTOMOBJECTSERVICE_QNAME, features);
    }

    public SalesCustomObjectService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SalesCustomObjectService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SalesCustomObjectService
     */
    @WebEndpoint(name = "SalesCustomObjectServiceSoapHttpPort")
    public SalesCustomObjectService getSalesCustomObjectServiceSoapHttpPort() {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/sales/custExtn/extnService/", "SalesCustomObjectServiceSoapHttpPort"), SalesCustomObjectService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SalesCustomObjectService
     */
    @WebEndpoint(name = "SalesCustomObjectServiceSoapHttpPort")
    public SalesCustomObjectService getSalesCustomObjectServiceSoapHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlns.oracle.com/apps/sales/custExtn/extnService/", "SalesCustomObjectServiceSoapHttpPort"), SalesCustomObjectService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SALESCUSTOMOBJECTSERVICE_EXCEPTION!= null) {
            throw SALESCUSTOMOBJECTSERVICE_EXCEPTION;
        }
        return SALESCUSTOMOBJECTSERVICE_WSDL_LOCATION;
    }

}
