
package com.hdr.ws.stubs.commonCustom;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CrmCommonReferenceService", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CrmCommonReferenceService {


    /**
     * 
     * @param objectName
     * @param object
     * @return
     *     returns java.lang.Object
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/createEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "createEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.CreateEntity")
    @ResponseWrapper(localName = "createEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.CreateEntityResponse")
    public Object createEntity(
        @WebParam(name = "object", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        Object object,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param objectName
     * @param keyValue
     * @return
     *     returns java.lang.Object
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/getEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "getEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetEntity")
    @ResponseWrapper(localName = "getEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetEntityResponse")
    public Object getEntity(
        @WebParam(name = "keyValue", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        List<String> keyValue,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param objectName
     * @param object
     * @return
     *     returns java.lang.Object
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/updateEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "updateEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.UpdateEntity")
    @ResponseWrapper(localName = "updateEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.UpdateEntityResponse")
    public Object updateEntity(
        @WebParam(name = "object", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        Object object,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param objectName
     * @param object
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/deleteEntity")
    @RequestWrapper(localName = "deleteEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.DeleteEntity")
    @ResponseWrapper(localName = "deleteEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.DeleteEntityResponse")
    public void deleteEntity(
        @WebParam(name = "object", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        Object object,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param findControl
     * @param objectName
     * @param findCriteria
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/findEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "findEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.FindEntity")
    @ResponseWrapper(localName = "findEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.FindEntityResponse")
    public List<Object> findEntity(
        @WebParam(name = "findCriteria", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        FindCriteria findCriteria,
        @WebParam(name = "findControl", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        FindControl findControl,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param objectName
     * @param object
     * @return
     *     returns java.lang.Object
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/mergeEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "mergeEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.MergeEntity")
    @ResponseWrapper(localName = "mergeEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.MergeEntityResponse")
    public Object mergeEntity(
        @WebParam(name = "object", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        Object object,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param processControl
     * @param objectName
     * @param changeOperation
     * @param object
     * @return
     *     returns java.util.List<java.lang.Object>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/processEntity")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "processEntity", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.ProcessEntity")
    @ResponseWrapper(localName = "processEntityResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.ProcessEntityResponse")
    public List<Object> processEntity(
        @WebParam(name = "changeOperation", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String changeOperation,
        @WebParam(name = "object", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        List<Object> object,
        @WebParam(name = "processControl", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        ProcessControl processControl,
        @WebParam(name = "objectName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String objectName)
        throws ServiceException
    ;

    /**
     * 
     * @param viewName
     * @param localeName
     * @return
     *     returns com.hdr.ws.stubs.commonCustom.ObjAttrHints
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/getDfltObjAttrHints")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "getDfltObjAttrHints", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetDfltObjAttrHints")
    @ResponseWrapper(localName = "getDfltObjAttrHintsResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetDfltObjAttrHintsResponse")
    public ObjAttrHints getDfltObjAttrHints(
        @WebParam(name = "viewName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String viewName,
        @WebParam(name = "localeName", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
        String localeName)
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/getServiceLastUpdateTime")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "getServiceLastUpdateTime", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetServiceLastUpdateTime")
    @ResponseWrapper(localName = "getServiceLastUpdateTimeResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetServiceLastUpdateTimeResponse")
    public XMLGregorianCalendar getServiceLastUpdateTime()
        throws ServiceException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.hdr.ws.stubs.commonCustom.ServiceViewInfo>
     * @throws ServiceException
     */
    @WebMethod(action = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/getEntityList")
    @WebResult(name = "result", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/")
    @RequestWrapper(localName = "getEntityList", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetEntityList")
    @ResponseWrapper(localName = "getEntityListResponse", targetNamespace = "http://xmlns.oracle.com/apps/cdm/foundation/custextn/extnService/types/", className = "com.hdr.ws.stubs.commonCustom.GetEntityListResponse")
    public List<ServiceViewInfo> getEntityList()
        throws ServiceException
    ;

}
